# calci

from tkinter import *
def click(event):
	global scvalue
	text=event.widget.cget("text")
	if (text=='='):
		if scvalue.get().isdigit():
			value=int(scvalue.get())
		else:
			try:
				value=eval(screen.get())
			except Exception as e:
				value="ERROR"
		scvalue.set(value)
		screen.update()
	elif(text=='<-'):
		value=scvalue.get()
		scvalue.set(value[:-1])
	elif(text=='C'):
		scvalue.set("")
		screen.update()
	else:
		scvalue.set(scvalue.get() + text)
		screen.update()
root=Tk()
scvalue=StringVar()
scvalue.set("")
screen=Entry(root,text=scvalue,font="lucida 18 bold")
screen.pack(pady=8)

f1=Frame(root,bg="grey")
b1=Button(f1,text="9",font="lucida 20 bold")
b1.bind("<Button-1>",click)
b1.pack(padx=30,pady=20,side="left")
b2=Button(f1,text="8",font="lucida 20 bold")
b2.bind("<Button-1>",click)
b2.pack(padx=30,pady=20,side="left")
b3=Button(f1,text="7",font="lucida 20 bold")
b3.bind("<Button-1>",click)
b3.pack(padx=30,pady=20,side="left")
b4=Button(f1,text="/",font="lucida 20 bold")
b4.bind("<Button-1>",click)
b4.pack(padx=30,pady=20,side="left")
f1.pack()

f2=Frame(root,bg="grey")
b1=Button(f2,text="6",font="lucida 20 bold")
b1.bind("<Button-1>",click)
b1.pack(padx=30,pady=20,side="left")
b2=Button(f2,text="5",font="lucida 20 bold")
b2.bind("<Button-1>",click)
b2.pack(padx=30,pady=20,side="left")
b3=Button(f2,text="4",font="lucida 20 bold")
b3.bind("<Button-1>",click)
b3.pack(padx=30,pady=20,side="left")
b4=Button(f2,text="*",font="lucida 20 bold")
b4.bind("<Button-1>",click)
b4.pack(padx=30,pady=20,side="left")
f2.pack()

f3=Frame(root,bg="grey")
b1=Button(f3,text="3",font="lucida 20 bold")
b1.bind("<Button-1>",click)
b1.pack(padx=30,pady=20,side="left")
b2=Button(f3,text="2",font="lucida 20 bold")
b2.bind("<Button-1>",click)
b2.pack(padx=30,pady=20,side="left")
b3=Button(f3,text="1",font="lucida 20 bold")
b3.bind("<Button-1>",click)
b3.pack(padx=30,pady=20,side="left")
b4=Button(f3,text="-",font="lucida 20 bold")
b4.bind("<Button-1>",click)
b4.pack(padx=30,pady=20,side="left")
f3.pack()

f4=Frame(root,bg="grey")
b1=Button(f4,text="C",font="lucida 20 bold")
b1.bind("<Button-1>",click)
b1.pack(padx=30,pady=20,side="left")
b2=Button(f4,text="0",font="lucida 20 bold")
b2.bind("<Button-1>",click)
b2.pack(padx=30,pady=20,side="left")
b3=Button(f4,text="=",font="lucida 20 bold")
b3.bind("<Button-1>",click)
b3.pack(padx=30,pady=20,side="left")
b4=Button(f4,text="+",font="lucida 20 bold")
b4.bind("<Button-1>",click)
b4.pack(padx=30,pady=20,side="right")
f4.pack()
f5=Frame(root,bg='grey')
b1=Button(f5,text="<-",font="lucida 20 bold")
b1.bind("<Button-1>",click)
b1.pack(padx=30,pady=20,side="left")
b2=Button(f5,text="%",font="lucida 20 bold")
b2.bind("<Button-1>",click)
b2.pack(padx=30,pady=20,side="left")
b3=Button(f5,text="(",font="lucida 20 bold")
b3.bind("<Button-1>",click)
b3.pack(padx=30,pady=20,side="left")
b4=Button(f5,text=")",font="lucida 20 bold")
b4.bind("<Button-1>",click)
b4.pack(padx=30,pady=20,side="left")
f5.pack()

root.mainloop()
